theme: jekyll-theme-minimal
title: Bioinformatics Introductory Course
logo: https://ecdn.teacherspayteachers.com/thumbitem/Genetics-Phenotype-and-Genotype-SpongeBob-Square-Pan-school-science-6762620-1657546501/original-6762620-1.jpg